### ISSUE TITLE
Not using subversion any more

### ISSUE THREAD

**Issue by hannob** [adfinis-sygroup/freewvs-wrapper#2]
I'm the original author of freewvs.

Not sure if you're still using this code, but it seems hardwired to our old subversion repo. I wanted to point out that we've been using git for a while. Find our current webpage here:
https://freewvs.schokokeks.org/
And our git repo here:
https://git.schokokeks.org/freewvs.git/

I'm also planning to provide a freewvs-db-update-script soon. Also happy to discuss if we can make freewvs more useful for others (e.g. your wrapper seems to mainly consume XML and output CSV - I tend to think we want to switch from xml to json in the medium-term, but I could probably add a CSV mode if that's what people want).

**Comment by karras** [comment]
Thanks for taking the time to let us know about the change from SVN to git! We've no longer any use for the wrapper and will therefore deprecate/archive the project as it is no longer in use and not maintained. Thanks for your understanding!
